### ISSUE TITLE
Javascript is blocked when page is requested over HTTPS

### ISSUE THREAD

**Issue by ebpitts** [ilbonte/rescuetime-again#9]
![screen shot 2016-04-29 at 3 21 44 pm](https://cloud.githubusercontent.com/assets/10963385/14928558/39ec526e-0e1e-11e6-8632-700cbb1de6ba.png)

The screenshot above is from Firefox 46's developer tools. Firefox is blocking the javascript on https://ilbonte.github.io/rescuetime-again/ from loading as explained in https://developer.mozilla.org/en-US/docs/Security/Mixed_content . The javascript needs to be loaded over https.

**Comment by ilbonte** [comment]
Strange I didn't get those errors with Firefox. I added the missing https, could you check now and let me know? Which OS are you using?

**Comment by ebpitts** [comment]
It's working now.
